default: &default-development
  adapter: sqlite3
  pool: 5
  timeout: 5000

default: &default-production
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: <%= ENV['RAILS_DATABASE_USERNAME'] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>

development:
  <<: *default-development
  database: db/development.sqlite3

test:
  <<: *default-development
  database: db/test.sqlite3

staging:
  <<: *default-production
  database: bacon_staging

production:
  <<: *default-production
  database: bacon_production
